site_name: "Portfolio"
theme:
  name: material
  language: es
  logo: assets/Logo_MJ.png        # <- tu logo (respeta mayúsculas)
  favicon: assets/placeholder.png
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox

# Configuración para copiar archivos adicionales
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/matias-jorda-b663642a3/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/MatiasJorda
      name: GitHub

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - assets/custom.css              # <- tu CSS

repo_url: https://github.com/MatiasJorda/INGENIERIA-DATOS
repo_name: MatiasJorda/INGENIERIA-DATOS
edit_uri: edit/main/docs/   # ruta para que el botón "Editar" funcione

nav:
  - Inicio: index.md
  - Acerca: acerca.md
  - Portfolio:
    - portfolio/index.md
    - UT1:
      - portfolio/UT1/01-Main.md
      - portfolio/UT1/01-Practica_1.md
      - portfolio/UT1/01-Practica_3.md
      - portfolio/UT1/01-Practica_4.md
    - UT2:
      - portfolio/UT2/02-Main.md
      - portfolio/UT2/02-Practica_5.md
      - portfolio/UT2/02-Practica_6.md
      - portfolio/UT2/02-Practica_7.md
      - Notebooks:
        - portfolio/UT2/Notebooks/Practica_5.ipynb
        - portfolio/UT2/Notebooks/Practica_6.ipynb
        - portfolio/UT2/Notebooks/Practica_7.ipynb
  - Recursos: recursos.md
